# Generated by Django 2.1.1 on 2019-01-30 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('bicycle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('color', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Borrow_history',
            fields=[
                ('borrow_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_day', models.DateField(blank=True, null=True)),
                ('bicycle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bicycle_borrow_sub_sys.Bicycle')),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_id', models.IntegerField(primary_key=True, serialize=False)),
                ('office_name', models.CharField(max_length=6)),
                ('bicycle_nums_office', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bicycle',
            name='office_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bicycle_borrow_sub_sys.Office'),
        ),
    ]
