# Generated by Django 2.1.1 on 2019-01-30 05:54

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('employee_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='社員番号')),
                ('username', models.CharField(max_length=10, verbose_name='社員名')),
                ('password', models.CharField(max_length=128, verbose_name='パスワード')),
                ('borrowed_bicycles', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='借りている自転車の数')),
                ('is_staff', models.BooleanField(default=False, verbose_name='管理者サイトへのアクセス権限')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='管理者サイトでの編集権限')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.EmployeeManager()),
            ],
        ),
    ]
